In [1]:
import pandas as pd
import numpy as np

In [2]:
raw1 = pd.read_csv("raw_text/b Feb22 100 1.csv", index_col=0)
raw2 = pd.read_csv("raw_text/b Feb22 100 2.csv", index_col=0)
raw3 = pd.read_csv("raw_text/b Feb22 100 3.csv", index_col=0)
raw4 = pd.read_csv("raw_text/b Feb22 100 4.csv", index_col=0)
raw5 = pd.read_csv("raw_text/b Feb22 100 5.csv", index_col=0)

raw_1 = pd.read_csv("raw_text/b Feb23 250 1.csv", index_col=0)
raw_2 = pd.read_csv("raw_text/b Feb23 250 2.csv", index_col=0)
raw_3 = pd.read_csv("raw_text/b Feb23 250 3.csv", index_col=0)
raw_4 = pd.read_csv("raw_text/b Feb23 250 4.csv", index_col=0)
raw_5 = pd.read_csv("raw_text/b Feb23 250 5.csv", index_col=0)
raw_6 = pd.read_csv("raw_text/b Feb23 250 6.csv", index_col=0)
raw_7 = pd.read_csv("raw_text/b Feb23 250 7.csv", index_col=0)
raw_8 = pd.read_csv("raw_text/b Feb23 250 8.csv", index_col=0)
raw_9 = pd.read_csv("raw_text/b Feb23 250 9.csv", index_col=0)
raw_10 = pd.read_csv("raw_text/b Feb23 250 10.csv", index_col=0)
raw_11 = pd.read_csv("raw_text/b Feb23 250 11.csv", index_col=0)
raw_12 = pd.read_csv("raw_text/b Feb23 250 12.csv", index_col=0)

raw__1 = pd.read_csv("raw_text/b Feb24 200 1.csv", index_col=0)
raw__2 = pd.read_csv("raw_text/b Feb24 200 2.csv", index_col=0)
raw__3 = pd.read_csv("raw_text/b Feb24 200 3.csv", index_col=0)
raw__4 = pd.read_csv("raw_text/b Feb24 200 4.csv", index_col=0)
raw__5 = pd.read_csv("raw_text/b Feb24 200 5.csv", index_col=0)
raw__6 = pd.read_csv("raw_text/b Feb24 200 6.csv", index_col=0)
raw__7 = pd.read_csv("raw_text/b Feb24 200 7.csv", index_col=0)
raw__8 = pd.read_csv("raw_text/b Feb24 200 8.csv", index_col=0)
raw__9 = pd.read_csv("raw_text/b Feb24 200 9.csv", index_col=0)
raw__10 = pd.read_csv("raw_text/b Feb24 200 10.csv", index_col=0)
raw__11 = pd.read_csv("raw_text/b Feb24 200 11.csv", index_col=0)
raw__12 = pd.read_csv("raw_text/b Feb24 200 12.csv", index_col=0)
raw__13 = pd.read_csv("raw_text/b Feb24 200 13.csv", index_col=0)
raw__14 = pd.read_csv("raw_text/b Feb24 200 14.csv", index_col=0)
raw__15 = pd.read_csv("raw_text/b Feb24 200 15.csv", index_col=0)

In [3]:
raw__1

                          The beer brand is similar to
0     its namesake, but with a touch of oak. It's a...
1     the popular Dom Perignon, but is made with a ...
2     the original, but it's not a traditional Amer...
3     the popular Miller Lite, but is made with a s...
4     the Budweiser brand, which was founded in 185...
..                                                 ...
195   the popular American beer, but with a slight ...
196   the popular British beer, Great Britain's Gre...
197   the popular Goose Island brand, which is the ...
198   Budweiser, but with a "new twist" and "new in...
199   the dark ale from the brewery's other flagshi...

[200 rows x 1 columns]

In [4]:
def process_responses(all_text,keywords,filename):
    frqs = {}
    for prompt in all_text.columns:
        frqs[prompt] = {}
        series = all_text[prompt].str.split("<|endoftext|>", expand=True)[0]
        for brand in keywords:
            cnt = pd.Series(np.zeros_like(series))
            for alias in brand:
                cnt = cnt | series.str.contains('\\b' + alias + '(?:[^A-z]|\\b)', case=False)
            frqs[prompt][brand[0]] = cnt.sum()
    return pd.DataFrame(frqs)

In [5]:
# brands = [
#     ['Budweiser'],
#     ['Bud Light'],
#     ['Michelob Ultra'],
#     ['Stella Artois'],
#     ['Patagonia Cerveza', "Cerveza Patagonia"],
#     ['Estrella Jalisco'],
#     ['Busch Beer', 'Busch'],
#     ['Natural Light', 'Natty Light', 'Natty'],
#     ['Landshark'],
#     ['Presidente'],
#     ['Hoegaarden'],
#     ['Shock Top'],
#     # brewers collective
#     ['10 Barrel'],
#     ['Appalachian Mountain Brewery', 'amb', 'Appalachian Mountain'],
#     ['Blue Point'],
#     ['Breckenridge Brewery', 'Breck', 'Breckenridge'],
#     ['Cisco Brewers'],
#     ['Devils Backbone'],
#     ['Elysian'],
#     ['Four Peaks'],
#     ['Golden Road'],
#     ['Goose Island'],
#     ['Karbach'],
#     ['Kona'],
#     ['LQD'],
#     ['Omission Brewing', 'Omission'],
#     ['Platform Beer'],
#     ['Red Hook'],
#     ['Square Mile Cider'],
#     ['Veza Sur'],
#     ['Virtue Cider'],
#     ['Wicked Weed'],
#     ['Widmer Brothers'],
#     ['Wynwood'],
#     # beyond beer
#     ['Ritas'],
#     ['Babe'], # sparkling rose
#     ['Bon Viv'],
#     ['Cacti'],
#     ['Cutwater']
# ]
brands = [["Budweiser"],
          ["Busch"],
          ["Sierra Nevada"],
          ["Coors"],
          ["Bud Light"],
          ["Goose Island"],
          ["Coors Light"],
          ["MillerCoors"],
          ["Corona"],
          ["Heineke"],
          ["Stella Artois"],
          ["Pabst"],
          ['Miller Lite'],
          ['Pilsner Urquell'],
          ['Stone'],
          ['Pabst Blue Ribbon'],
          ['Sierra Nevada Pale Ale'],
          ['Blue Moon'],
          ['Sierra Nevada Brewing'],
          ['Stone Brewing'],
          ['Golden Road'],
          ['Kona'],
          ['Pacific Northwest'],
          ['New Belgium Brewing'],
          ['Kolsch'],
          ['Corona Extra'],
          ['Hopworks'],
          ['Samuel Adams'],
          ['Hefeweizen'],
          ['Kirin'],
          ['Belgian Witbier'],
          ['Lagunitas Brewing'],
          ['Guiness'],
          ['Belgian White'],
          ['Miller High Life'],
          ['Dos Equis'],
          ['Michelob Ultra'],
          ['Rolling Rock'],
          ['Red Stripe']]

In [6]:
f1 = process_responses(raw1, brands, "")
f2 = process_responses(raw2, brands, "")
f3 = process_responses(raw3, brands, "")
f4 = process_responses(raw4, brands, "")
f5 = process_responses(raw5, brands, "")

f_1 = process_responses(raw_1, brands, "")
f_2 = process_responses(raw_2, brands, "")
f_3 = process_responses(raw_3, brands, "")
f_4 = process_responses(raw_4, brands, "")
f_5 = process_responses(raw_5, brands, "")
f_6 = process_responses(raw_6, brands, "")
f_7 = process_responses(raw_7, brands, "")
f_8 = process_responses(raw_8, brands, "")
f_9 = process_responses(raw_9, brands, "")
f_10 = process_responses(raw_10, brands, "")
f_11 = process_responses(raw_11, brands, "")
f_12 = process_responses(raw_12, brands, "")

f__1 = process_responses(raw__1, brands, "")
f__2 = process_responses(raw__2, brands, "")
f__3 = process_responses(raw__3, brands, "")
f__4 = process_responses(raw__4, brands, "")
f__5 = process_responses(raw__5, brands, "")
f__6 = process_responses(raw__6, brands, "")
f__7 = process_responses(raw__7, brands, "")
f__8 = process_responses(raw__8, brands, "")
f__9 = process_responses(raw__9, brands, "")
f__10 = process_responses(raw__10, brands, "")
f__11 = process_responses(raw__11, brands, "")
f__12 = process_responses(raw__12, brands, "")
f__13 = process_responses(raw__13, brands, "")
f__14 = process_responses(raw__14, brands, "")
f__15 = process_responses(raw__15, brands, "")

In [7]:
joined = f1+f2+f3+f4+f5+f_1+f_2+f_3+f_4+f_5+f_6+f_7+f_8+f_9+f_10+f_11+f_12+f__1+f__2+f__3+f__4+f__5+f__6+f__7+f__8+f__9+f__10+f__11+f__12+f__13+f__14+f__15

In [8]:
joined

                        The beer brand is similar to
Belgian White                                      2
Belgian Witbier                                   14
Blue Moon                                         71
Bud Light                                        304
Budweiser                                       1104
Busch                                            366
Coors                                            314
Coors Light                                      254
Corona                                           188
Corona Extra                                      18
Dos Equis                                          0
Golden Road                                       47
Goose Island                                     303
Guiness                                            0
Hefeweizen                                        16
Heineke                                            0
Hopworks                                          18
Kirin                                             16
Kolsch                                            30
Kona                                              36
Lagunitas Brewing                                 12
Michelob Ultra                                     1
Miller High Life                                   7
Miller Lite                                      121
MillerCoors                                      252
New Belgium Brewing                               33
Pabst                                            130
Pabst Blue Ribbon                                 90
Pacific Northwest                                 34
Pilsner Urquell                                  108
Red Stripe                                         0
Rolling Rock                                       0
Samuel Adams                                      17
Sierra Nevada                                    325
Sierra Nevada Brewing                             71
Sierra Nevada Pale Ale                            74
Stella Artois                                    151
Stone                                             95
Stone Brewing                                     47

In [9]:
joined.to_csv("freqs/jb reparse Apr16 6500.csv")