In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("freqs/Nov28 40 1.csv")
df2 = pd.read_csv("freqs/Nov28 40 2.csv")
df3 = pd.read_csv("freqs/Nov28 40 3.csv")
df4 = pd.read_csv("freqs/Nov28 40 4.csv")
df5 = pd.read_csv("freqs/Nov28 40 5.csv")
df6 = pd.read_csv("freqs/Nov28 40 6.csv")
df7 = pd.read_csv("freqs/Nov28 40 7.csv")
df8 = pd.read_csv("freqs/Nov28 40 8.csv")
df9 = pd.read_csv("freqs/Nov28 40 9.csv")
df10 = pd.read_csv("freqs/Nov28 40 10.csv")

In [3]:
df1

,Unnamed: 0,The car brand Jeep is similar to,The car brand Subaru is similar to,The car brand Dodge is similar to,The car brand Tesla is similar to,The car brand Toyota is similar to,The car brand Honda is similar to,The car brand Nissan is similar to,The car brand Chevrolet is similar to,The car brand Hyundai is similar to,...,The car brand Lamborghini is similar to,The car brand Mercedes-Benz is similar to,The car brand BMW is similar to,The car brand Ford is similar to,The car brand Porsche is similar to,The car brand Audi is similar to,The car brand Volkswagen is similar to,The car brand Ferrari is similar to,The car brand Lexus is similar to,The car brand Volvo is similar to
0,Jeep,36,1,2,0,0,2,1,0,1,...,0,0,0,2,0,1,1,6,0,0
1,Subaru,0,37,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,Dodge,1,1,37,0,0,0,0,1,0,...,0,0,0,0,0,0,0,2,0,0
3,Tesla,3,2,0,36,1,1,2,11,6,...,2,2,3,6,6,6,3,4,4,4
4,Toyota,2,7,4,4,37,13,11,9,8,...,0,1,2,5,2,1,4,4,8,3
5,Honda,0,6,2,0,5,37,2,3,4,...,1,0,4,5,0,1,4,1,1,1
6,Nissan,0,0,1,2,4,4,36,2,2,...,1,0,1,5,1,1,1,0,0,0
7,Chevrolet,1,0,3,1,1,2,3,23,0,...,0,0,1,3,0,2,0,2,0,0
8,Hyundai,0,0,1,0,0,2,2,0,30,...,0,0,0,2,0,1,1,0,2,0
9,Mazda,0,0,0,0,0,2,0,1,1,...,0,0,0,1,0,1,1,0,0,0
10,Renault,0,0,1,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
11,Lamborghini,0,0,0,0,0,0,0,0,0,...,39,1,0,0,1,1,0,0,0,0
12,Mercedes-Benz,1,6,3,2,5,7,10,4,4,...,3,33,13,8,7,12,5,12,13,9
13,BMW,4,10,9,4,5,13,9,2,7,...,2,14,31,16,10,12,5,8,14,12
14,Ford,23,11,18,16,19,8,4,17,14,...,5,3,8,33,6,2,10,2,3,14
15,Porsche,1,2,2,2,1,1,1,0,0,...,1,4,3,6,35,9,4,5,3,2
16,Audi,3,1,1,0,3,3,0,1,0,...,3,1,3,3,6,30,2,1,4,1
17,Volkswagen,1,11,3,4,9,4,7,1,7,...,1,1,5,10,2,13,24,3,4,1
18,Ferrari,2,1,0,0,0,1,2,1,0,...,22,7,1,2,5,2,1,27,0,0
19,Lexus,0,0,0,0,3,1,1,0,1,...,0,0,0,1,2,0,1,0,35,0
20,Volvo,0,0,0,0,0,1,2,0,0,...,0,1,2,1,0,0,1,0,1,30

In [4]:
df2

,Unnamed: 0,The car brand Jeep is similar to,The car brand Subaru is similar to,The car brand Dodge is similar to,The car brand Tesla is similar to,The car brand Toyota is similar to,The car brand Honda is similar to,The car brand Nissan is similar to,The car brand Chevrolet is similar to,The car brand Hyundai is similar to,...,The car brand Lamborghini is similar to,The car brand Mercedes-Benz is similar to,The car brand BMW is similar to,The car brand Ford is similar to,The car brand Porsche is similar to,The car brand Audi is similar to,The car brand Volkswagen is similar to,The car brand Ferrari is similar to,The car brand Lexus is similar to,The car brand Volvo is similar to
0,Jeep,32,1,4,0,0,0,1,1,1,...,1,0,0,1,0,0,1,4,0,0
1,Subaru,1,39,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,Dodge,1,0,33,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Tesla,1,0,1,37,5,1,4,6,4,...,3,4,2,7,6,3,2,6,3,4
4,Toyota,9,8,7,1,34,5,3,4,11,...,0,2,2,7,0,1,4,1,11,0
5,Honda,2,3,3,0,5,36,2,3,5,...,0,2,2,2,0,1,6,0,7,1
6,Nissan,2,1,0,1,6,1,35,2,1,...,0,1,5,1,0,0,0,2,1,0
7,Chevrolet,3,0,3,4,0,1,1,24,1,...,0,1,1,1,1,2,3,2,0,1
8,Hyundai,0,1,0,1,2,1,1,0,31,...,0,0,0,0,0,0,2,0,1,0
9,Mazda,1,0,1,0,0,0,0,0,0,...,0,0,1,2,0,0,0,0,1,0
10,Renault,0,0,0,1,0,1,1,0,1,...,0,0,2,2,0,0,0,0,1,1
11,Lamborghini,0,0,0,0,0,0,0,0,0,...,35,0,1,0,0,3,0,0,1,0
12,Mercedes-Benz,1,5,6,4,5,15,6,3,3,...,9,29,21,7,3,14,3,11,7,12
13,BMW,1,12,11,14,7,10,6,2,2,...,3,8,38,8,8,18,4,10,15,9
14,Ford,22,8,20,9,9,3,8,28,16,...,5,3,4,35,7,5,16,4,4,13
15,Porsche,0,0,4,2,1,1,4,0,1,...,4,2,4,1,37,10,2,5,5,1
16,Audi,2,0,1,1,1,1,1,1,3,...,2,3,2,1,4,34,6,2,4,3
17,Volkswagen,2,9,7,5,8,5,14,3,12,...,0,4,4,5,7,5,30,2,5,4
18,Ferrari,3,2,0,2,0,7,2,1,1,...,26,0,1,0,6,1,0,29,2,0
19,Lexus,1,0,0,0,4,0,0,0,1,...,0,0,0,0,0,0,0,0,34,0
20,Volvo,0,0,0,0,0,1,2,0,0,...,0,0,0,2,0,2,0,0,1,31

In [5]:
joined = df1+df2+df3+df4+df5+df6+df7+df8+df9+df10
joined

,Unnamed: 0,The car brand Jeep is similar to,The car brand Subaru is similar to,The car brand Dodge is similar to,The car brand Tesla is similar to,The car brand Toyota is similar to,The car brand Honda is similar to,The car brand Nissan is similar to,The car brand Chevrolet is similar to,The car brand Hyundai is similar to,...,The car brand Lamborghini is similar to,The car brand Mercedes-Benz is similar to,The car brand BMW is similar to,The car brand Ford is similar to,The car brand Porsche is similar to,The car brand Audi is similar to,The car brand Volkswagen is similar to,The car brand Ferrari is similar to,The car brand Lexus is similar to,The car brand Volvo is similar to
0,JeepJeepJeepJeepJeepJeepJeepJeepJeepJeep,320,8,27,4,5,6,5,17,5,...,10,7,2,20,1,5,9,35,5,2
1,SubaruSubaruSubaruSubaruSubaruSubaruSubaruSuba...,11,372,4,0,2,4,8,4,2,...,1,1,1,3,0,3,0,0,2,2
2,DodgeDodgeDodgeDodgeDodgeDodgeDodgeDodgeDodgeD...,9,3,320,0,2,0,0,5,1,...,0,1,1,5,0,1,0,3,1,0
3,TeslaTeslaTeslaTeslaTeslaTeslaTeslaTeslaTeslaT...,26,10,10,354,31,13,39,60,36,...,38,54,33,29,45,37,29,32,37,50
4,ToyotaToyotaToyotaToyotaToyotaToyotaToyotaToyo...,58,103,46,35,342,102,79,45,85,...,3,20,29,54,13,10,38,20,84,25
5,HondaHondaHondaHondaHondaHondaHondaHondaHondaH...,13,52,21,6,46,344,26,18,33,...,7,11,11,26,4,6,18,11,35,18
6,NissanNissanNissanNissanNissanNissanNissanNiss...,11,23,18,21,36,30,350,15,21,...,2,7,13,20,5,6,11,11,19,15
7,ChevroletChevroletChevroletChevroletChevroletC...,27,8,41,17,13,11,25,250,10,...,1,5,7,25,4,14,13,12,7,13
8,HyundaiHyundaiHyundaiHyundaiHyundaiHyundaiHyun...,7,13,9,2,11,10,12,1,328,...,1,2,2,5,1,1,8,1,9,7
9,MazdaMazdaMazdaMazdaMazdaMazdaMazdaMazdaMazdaM...,3,10,5,0,7,9,2,5,4,...,0,5,3,12,2,2,1,3,5,0
10,RenaultRenaultRenaultRenaultRenaultRenaultRena...,2,2,2,2,7,9,7,1,6,...,3,2,2,8,1,2,2,5,3,4
11,LamborghiniLamborghiniLamborghiniLamborghiniLa...,0,0,2,2,3,0,0,3,0,...,371,5,1,0,6,7,3,11,3,0
12,Mercedes-BenzMercedes-BenzMercedes-BenzMercede...,28,42,56,51,57,76,54,33,39,...,72,274,166,61,65,129,65,129,97,90
13,BMWBMWBMWBMWBMWBMWBMWBMWBMWBMW,26,80,86,125,53,77,76,21,54,...,26,116,324,104,77,137,53,86,128,92
14,FordFordFordFordFordFordFordFordFordFord,241,89,192,111,120,71,83,252,141,...,39,41,69,352,74,39,106,29,63,154
15,PorschePorschePorschePorschePorschePorschePors...,7,13,23,14,16,15,19,14,11,...,39,28,36,27,339,66,49,53,28,19
16,AudiAudiAudiAudiAudiAudiAudiAudiAudiAudi,18,15,12,14,9,15,18,15,21,...,18,28,41,18,36,336,71,25,48,15
17,VolkswagenVolkswagenVolkswagenVolkswagenVolksw...,27,95,40,41,72,43,85,30,90,...,16,35,45,67,45,75,268,28,49,25
18,FerrariFerrariFerrariFerrariFerrariFerrariFerr...,15,7,6,13,13,25,16,6,18,...,231,31,11,10,61,30,11,310,15,9
19,LexusLexusLexusLexusLexusLexusLexusLexusLexusL...,5,1,3,2,21,5,1,4,7,...,0,3,0,3,2,0,2,4,350,0
20,VolvoVolvoVolvoVolvoVolvoVolvoVolvoVolvoVolvoV...,2,2,3,3,2,2,8,2,3,...,1,3,5,11,1,4,2,0,8,292

In [6]:
joined['Unnamed: 0'] = df1['Unnamed: 0']

In [7]:
joined

,Unnamed: 0,The car brand Jeep is similar to,The car brand Subaru is similar to,The car brand Dodge is similar to,The car brand Tesla is similar to,The car brand Toyota is similar to,The car brand Honda is similar to,The car brand Nissan is similar to,The car brand Chevrolet is similar to,The car brand Hyundai is similar to,...,The car brand Lamborghini is similar to,The car brand Mercedes-Benz is similar to,The car brand BMW is similar to,The car brand Ford is similar to,The car brand Porsche is similar to,The car brand Audi is similar to,The car brand Volkswagen is similar to,The car brand Ferrari is similar to,The car brand Lexus is similar to,The car brand Volvo is similar to
0,Jeep,320,8,27,4,5,6,5,17,5,...,10,7,2,20,1,5,9,35,5,2
1,Subaru,11,372,4,0,2,4,8,4,2,...,1,1,1,3,0,3,0,0,2,2
2,Dodge,9,3,320,0,2,0,0,5,1,...,0,1,1,5,0,1,0,3,1,0
3,Tesla,26,10,10,354,31,13,39,60,36,...,38,54,33,29,45,37,29,32,37,50
4,Toyota,58,103,46,35,342,102,79,45,85,...,3,20,29,54,13,10,38,20,84,25
5,Honda,13,52,21,6,46,344,26,18,33,...,7,11,11,26,4,6,18,11,35,18
6,Nissan,11,23,18,21,36,30,350,15,21,...,2,7,13,20,5,6,11,11,19,15
7,Chevrolet,27,8,41,17,13,11,25,250,10,...,1,5,7,25,4,14,13,12,7,13
8,Hyundai,7,13,9,2,11,10,12,1,328,...,1,2,2,5,1,1,8,1,9,7
9,Mazda,3,10,5,0,7,9,2,5,4,...,0,5,3,12,2,2,1,3,5,0
10,Renault,2,2,2,2,7,9,7,1,6,...,3,2,2,8,1,2,2,5,3,4
11,Lamborghini,0,0,2,2,3,0,0,3,0,...,371,5,1,0,6,7,3,11,3,0
12,Mercedes-Benz,28,42,56,51,57,76,54,33,39,...,72,274,166,61,65,129,65,129,97,90
13,BMW,26,80,86,125,53,77,76,21,54,...,26,116,324,104,77,137,53,86,128,92
14,Ford,241,89,192,111,120,71,83,252,141,...,39,41,69,352,74,39,106,29,63,154
15,Porsche,7,13,23,14,16,15,19,14,11,...,39,28,36,27,339,66,49,53,28,19
16,Audi,18,15,12,14,9,15,18,15,21,...,18,28,41,18,36,336,71,25,48,15
17,Volkswagen,27,95,40,41,72,43,85,30,90,...,16,35,45,67,45,75,268,28,49,25
18,Ferrari,15,7,6,13,13,25,16,6,18,...,231,31,11,10,61,30,11,310,15,9
19,Lexus,5,1,3,2,21,5,1,4,7,...,0,3,0,3,2,0,2,4,350,0
20,Volvo,2,2,3,3,2,2,8,2,3,...,1,3,5,11,1,4,2,0,8,292

In [8]:
joined.to_csv("freqs/j Nov 28 400.csv")