In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("freqs/Dec1 30 1.csv")
df2 = pd.read_csv("freqs/Dec1 30 2.csv")
df3 = pd.read_csv("freqs/Dec1 30 3.csv")
df4 = pd.read_csv("freqs/Dec1 30 4.csv")
df5 = pd.read_csv("freqs/Dec1 30 5.csv")
df6 = pd.read_csv("freqs/Dec1 30 6.csv")
df7 = pd.read_csv("freqs/Dec1 30 7.csv")
df8 = pd.read_csv("freqs/Dec1 30 8.csv")
df9 = pd.read_csv("freqs/Dec1 30 9.csv")
df10 = pd.read_csv("freqs/Dec1 30 10.csv")
df11 = pd.read_csv("freqs/Dec1 30 11.csv")
df12 = pd.read_csv("freqs/Dec1 30 12.csv")
df13 = pd.read_csv("freqs/Dec1 30 13.csv")
df14 = pd.read_csv("freqs/Dec1 30 14.csv")
df15 = pd.read_csv("freqs/Dec1 30 15.csv")

In [3]:
df1

,Unnamed: 0,The car brand Jeep is similar to,The car brand Subaru is similar to,The car brand Dodge is similar to,The car brand Tesla is similar to,The car brand Toyota is similar to,The car brand Honda is similar to,The car brand Nissan is similar to,The car brand Chevrolet is similar to,The car brand Hyundai is similar to,...,The car brand Lamborghini is similar to,The car brand Mercedes-Benz is similar to,The car brand BMW is similar to,The car brand Ford is similar to,The car brand Porsche is similar to,The car brand Audi is similar to,The car brand Volkswagen is similar to,The car brand Ferrari is similar to,The car brand Lexus is similar to,The car brand Volvo is similar to
0,Jeep,22,0,6,1,2,0,1,0,3,...,0,2,1,3,0,1,0,5,0,0
1,Subaru,0,27,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Dodge,1,0,22,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,Tesla,2,1,0,25,1,0,3,3,3,...,4,2,1,1,4,6,3,0,1,5
4,Toyota,4,8,3,1,23,10,6,2,1,...,3,2,1,4,2,2,2,1,9,6
5,Honda,1,4,0,1,5,25,1,2,1,...,1,1,2,1,2,1,0,2,3,3
6,Nissan,1,0,0,1,3,3,25,2,3,...,1,0,0,0,1,1,2,0,1,0
7,Chevrolet,1,1,5,0,0,0,1,19,2,...,0,2,0,0,0,4,3,1,1,0
8,Hyundai,0,2,0,1,2,1,0,1,21,...,0,0,0,1,0,1,0,0,0,0
9,Mazda,0,1,0,0,0,0,1,1,1,...,0,0,0,1,0,0,1,0,0,0
10,Renault,0,0,0,0,1,0,0,0,0,...,1,1,0,0,0,0,0,3,2,0
11,Lamborghini,0,0,1,0,0,1,0,0,0,...,28,1,0,0,0,0,1,2,0,0
12,Mercedes-Benz,2,2,2,5,1,7,5,2,2,...,6,19,9,4,8,10,5,6,6,5
13,BMW,3,8,2,14,4,6,4,3,2,...,3,9,23,5,6,10,5,7,11,1
14,Ford,16,7,14,1,10,4,8,17,10,...,3,2,5,27,4,1,10,4,4,12
15,Porsche,0,1,1,3,1,2,1,0,0,...,3,3,4,1,29,6,2,7,3,2
16,Audi,1,0,0,2,1,1,1,0,0,...,2,0,3,1,4,20,6,1,2,1
17,Volkswagen,1,9,3,5,7,2,7,3,5,...,1,5,3,6,6,3,21,4,4,0
18,Ferrari,0,0,0,0,1,1,1,3,3,...,14,3,2,0,3,2,0,24,1,0
19,Lexus,2,0,0,0,0,1,0,2,0,...,0,0,0,0,0,0,0,0,24,0
20,Volvo,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,18

In [4]:
df2

,Unnamed: 0,The car brand Jeep is similar to,The car brand Subaru is similar to,The car brand Dodge is similar to,The car brand Tesla is similar to,The car brand Toyota is similar to,The car brand Honda is similar to,The car brand Nissan is similar to,The car brand Chevrolet is similar to,The car brand Hyundai is similar to,...,The car brand Lamborghini is similar to,The car brand Mercedes-Benz is similar to,The car brand BMW is similar to,The car brand Ford is similar to,The car brand Porsche is similar to,The car brand Audi is similar to,The car brand Volkswagen is similar to,The car brand Ferrari is similar to,The car brand Lexus is similar to,The car brand Volvo is similar to
0,Jeep,27,0,1,1,1,0,1,0,3,...,2,0,0,3,0,1,1,2,0,0
1,Subaru,1,29,0,0,1,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Dodge,1,0,25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Tesla,0,2,0,28,3,2,1,3,6,...,1,3,4,4,1,4,4,3,0,4
4,Toyota,2,12,2,0,27,7,5,3,5,...,1,2,1,4,2,2,6,0,4,0
5,Honda,0,6,3,0,6,26,2,0,1,...,0,0,0,1,1,1,1,0,5,0
6,Nissan,0,3,5,1,2,3,25,0,1,...,0,1,0,1,1,0,3,1,0,1
7,Chevrolet,2,0,6,0,0,0,0,18,0,...,0,0,1,4,0,2,3,1,0,0
8,Hyundai,0,1,0,0,4,1,1,1,23,...,0,0,0,1,0,0,0,0,1,0
9,Mazda,0,1,0,1,1,4,0,0,0,...,0,0,0,0,0,1,0,0,0,0
10,Renault,0,0,0,0,0,0,3,0,0,...,0,0,1,1,0,1,1,1,0,0
11,Lamborghini,0,0,1,0,0,0,0,0,0,...,25,0,1,0,1,0,0,0,0,0
12,Mercedes-Benz,2,1,4,7,8,5,3,4,4,...,5,20,16,5,4,8,5,14,11,5
13,BMW,1,8,7,11,7,2,5,3,9,...,3,8,27,9,6,9,2,8,11,6
14,Ford,22,5,16,7,8,8,6,18,7,...,1,5,3,27,3,2,7,1,3,12
15,Porsche,0,1,4,2,1,0,1,0,3,...,0,1,2,3,29,6,2,3,3,2
16,Audi,0,0,1,1,1,0,0,0,5,...,1,3,2,1,4,23,6,1,5,3
17,Volkswagen,2,7,2,6,4,2,6,4,6,...,3,3,0,3,2,6,17,3,1,1
18,Ferrari,0,0,0,1,2,4,2,0,0,...,15,0,4,1,7,1,0,20,2,0
19,Lexus,0,0,1,0,1,0,0,0,2,...,0,1,0,1,0,0,0,0,26,0
20,Volvo,1,0,1,0,1,1,2,0,2,...,0,1,0,1,0,0,0,0,0,25

In [5]:
joined = df1+df2+df3+df4+df5+df6+df7+df8+df9+df10+df11+df12+df13+df14+df15
joined

,Unnamed: 0,The car brand Jeep is similar to,The car brand Subaru is similar to,The car brand Dodge is similar to,The car brand Tesla is similar to,The car brand Toyota is similar to,The car brand Honda is similar to,The car brand Nissan is similar to,The car brand Chevrolet is similar to,The car brand Hyundai is similar to,...,The car brand Lamborghini is similar to,The car brand Mercedes-Benz is similar to,The car brand BMW is similar to,The car brand Ford is similar to,The car brand Porsche is similar to,The car brand Audi is similar to,The car brand Volkswagen is similar to,The car brand Ferrari is similar to,The car brand Lexus is similar to,The car brand Volvo is similar to
0,JeepJeepJeepJeepJeepJeepJeepJeepJeepJeepJeepJe...,364,6,40,8,9,9,7,12,14,...,11,10,6,17,4,6,5,43,5,2
1,SubaruSubaruSubaruSubaruSubaruSubaruSubaruSuba...,6,411,3,0,6,2,3,2,3,...,0,1,2,1,0,0,3,1,4,1
2,DodgeDodgeDodgeDodgeDodgeDodgeDodgeDodgeDodgeD...,11,1,351,0,1,1,1,2,1,...,0,2,2,3,3,0,1,2,0,0
3,TeslaTeslaTeslaTeslaTeslaTeslaTeslaTeslaTeslaT...,20,21,9,395,29,17,46,56,50,...,34,63,49,29,49,47,48,23,37,53
4,ToyotaToyotaToyotaToyotaToyotaToyotaToyotaToyo...,63,110,43,26,367,141,90,50,82,...,10,29,30,60,29,18,46,19,90,24
5,HondaHondaHondaHondaHondaHondaHondaHondaHondaH...,15,62,21,11,64,392,26,23,27,...,7,12,20,20,6,10,16,13,42,10
6,NissanNissanNissanNissanNissanNissanNissanNiss...,13,21,23,14,47,50,386,20,21,...,2,12,11,10,8,15,17,17,20,11
7,ChevroletChevroletChevroletChevroletChevroletC...,24,9,50,14,16,15,19,291,9,...,3,9,10,31,7,13,14,15,8,5
8,HyundaiHyundaiHyundaiHyundaiHyundaiHyundaiHyun...,5,8,8,4,25,15,6,8,336,...,0,3,2,11,2,4,4,4,8,9
9,MazdaMazdaMazdaMazdaMazdaMazdaMazdaMazdaMazdaM...,4,10,3,3,11,17,8,4,10,...,0,3,3,10,0,1,5,4,7,1
10,RenaultRenaultRenaultRenaultRenaultRenaultRena...,1,4,1,0,6,6,20,4,4,...,3,7,1,4,2,5,7,13,3,2
11,LamborghiniLamborghiniLamborghiniLamborghiniLa...,1,0,2,0,0,1,4,3,4,...,412,3,4,3,8,2,3,12,1,2
12,Mercedes-BenzMercedes-BenzMercedes-BenzMercede...,36,36,52,82,57,76,64,37,53,...,78,302,173,81,91,152,74,162,109,100
13,BMWBMWBMWBMWBMWBMWBMWBMWBMWBMWBMWBMWBMWBMWBMW,28,92,86,128,78,72,69,35,75,...,25,130,364,106,81,150,76,90,140,99
14,FordFordFordFordFordFordFordFordFordFordFordFo...,277,102,237,108,122,89,97,279,132,...,42,50,68,394,84,37,122,43,83,157
15,PorschePorschePorschePorschePorschePorschePors...,6,14,21,18,23,16,25,17,16,...,37,39,39,31,380,75,44,48,33,19
16,AudiAudiAudiAudiAudiAudiAudiAudiAudiAudiAudiAu...,8,15,16,16,17,11,16,17,29,...,18,36,48,27,35,347,89,22,52,17
17,VolkswagenVolkswagenVolkswagenVolkswagenVolksw...,24,108,45,53,69,56,74,37,91,...,19,56,42,97,75,62,319,41,35,25
18,FerrariFerrariFerrariFerrariFerrariFerrariFerr...,12,10,5,11,10,24,30,12,30,...,255,29,18,13,81,40,7,318,25,7
19,LexusLexusLexusLexusLexusLexusLexusLexusLexusL...,3,4,9,0,16,6,2,7,6,...,2,3,3,2,3,1,2,0,393,1
20,VolvoVolvoVolvoVolvoVolvoVolvoVolvoVolvoVolvoV...,5,1,3,3,1,4,9,3,8,...,1,9,2,11,1,3,1,0,3,338

In [6]:
joined['Unnamed: 0'] = df1['Unnamed: 0']

In [7]:
joined

,Unnamed: 0,The car brand Jeep is similar to,The car brand Subaru is similar to,The car brand Dodge is similar to,The car brand Tesla is similar to,The car brand Toyota is similar to,The car brand Honda is similar to,The car brand Nissan is similar to,The car brand Chevrolet is similar to,The car brand Hyundai is similar to,...,The car brand Lamborghini is similar to,The car brand Mercedes-Benz is similar to,The car brand BMW is similar to,The car brand Ford is similar to,The car brand Porsche is similar to,The car brand Audi is similar to,The car brand Volkswagen is similar to,The car brand Ferrari is similar to,The car brand Lexus is similar to,The car brand Volvo is similar to
0,Jeep,364,6,40,8,9,9,7,12,14,...,11,10,6,17,4,6,5,43,5,2
1,Subaru,6,411,3,0,6,2,3,2,3,...,0,1,2,1,0,0,3,1,4,1
2,Dodge,11,1,351,0,1,1,1,2,1,...,0,2,2,3,3,0,1,2,0,0
3,Tesla,20,21,9,395,29,17,46,56,50,...,34,63,49,29,49,47,48,23,37,53
4,Toyota,63,110,43,26,367,141,90,50,82,...,10,29,30,60,29,18,46,19,90,24
5,Honda,15,62,21,11,64,392,26,23,27,...,7,12,20,20,6,10,16,13,42,10
6,Nissan,13,21,23,14,47,50,386,20,21,...,2,12,11,10,8,15,17,17,20,11
7,Chevrolet,24,9,50,14,16,15,19,291,9,...,3,9,10,31,7,13,14,15,8,5
8,Hyundai,5,8,8,4,25,15,6,8,336,...,0,3,2,11,2,4,4,4,8,9
9,Mazda,4,10,3,3,11,17,8,4,10,...,0,3,3,10,0,1,5,4,7,1
10,Renault,1,4,1,0,6,6,20,4,4,...,3,7,1,4,2,5,7,13,3,2
11,Lamborghini,1,0,2,0,0,1,4,3,4,...,412,3,4,3,8,2,3,12,1,2
12,Mercedes-Benz,36,36,52,82,57,76,64,37,53,...,78,302,173,81,91,152,74,162,109,100
13,BMW,28,92,86,128,78,72,69,35,75,...,25,130,364,106,81,150,76,90,140,99
14,Ford,277,102,237,108,122,89,97,279,132,...,42,50,68,394,84,37,122,43,83,157
15,Porsche,6,14,21,18,23,16,25,17,16,...,37,39,39,31,380,75,44,48,33,19
16,Audi,8,15,16,16,17,11,16,17,29,...,18,36,48,27,35,347,89,22,52,17
17,Volkswagen,24,108,45,53,69,56,74,37,91,...,19,56,42,97,75,62,319,41,35,25
18,Ferrari,12,10,5,11,10,24,30,12,30,...,255,29,18,13,81,40,7,318,25,7
19,Lexus,3,4,9,0,16,6,2,7,6,...,2,3,3,2,3,1,2,0,393,1
20,Volvo,5,1,3,3,1,4,9,3,8,...,1,9,2,11,1,3,1,0,3,338

In [8]:
joined.to_csv("freqs/j Dec 1 450.csv")