In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("freqs/Nov30 30 1.csv")
df2 = pd.read_csv("freqs/Nov30 30 2.csv")
df3 = pd.read_csv("freqs/Nov30 30 3.csv")
df4 = pd.read_csv("freqs/Nov30 30 4.csv")
df5 = pd.read_csv("freqs/Nov30 30 5.csv")
df6 = pd.read_csv("freqs/Nov30 30 6.csv")
df7 = pd.read_csv("freqs/Nov30 30 7.csv")
df8 = pd.read_csv("freqs/Nov30 30 8.csv")
df9 = pd.read_csv("freqs/Nov30 30 9.csv")
df10 = pd.read_csv("freqs/Nov30 30 10.csv")
df11 = pd.read_csv("freqs/Nov30 30 11.csv")
df12 = pd.read_csv("freqs/Nov30 30 12.csv")
df13 = pd.read_csv("freqs/Nov30 30 13.csv")
df14 = pd.read_csv("freqs/Nov30 30 14.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'freqs/Nov30 30 12.csv'

In [3]:
df1

,Unnamed: 0,The car brand Jeep is similar to,The car brand Subaru is similar to,The car brand Dodge is similar to,The car brand Tesla is similar to,The car brand Toyota is similar to,The car brand Honda is similar to,The car brand Nissan is similar to,The car brand Chevrolet is similar to,The car brand Hyundai is similar to,...,The car brand Lamborghini is similar to,The car brand Mercedes-Benz is similar to,The car brand BMW is similar to,The car brand Ford is similar to,The car brand Porsche is similar to,The car brand Audi is similar to,The car brand Volkswagen is similar to,The car brand Ferrari is similar to,The car brand Lexus is similar to,The car brand Volvo is similar to
0,Jeep,24,0,1,0,1,0,0,1,2,...,0,0,1,3,0,0,1,1,0,1
1,Subaru,0,27,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,Dodge,3,0,25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Tesla,2,0,1,25,0,1,6,6,5,...,3,2,5,1,4,2,3,0,4,3
4,Toyota,6,9,1,3,23,10,7,4,7,...,0,1,2,5,2,2,4,3,6,1
5,Honda,1,4,0,4,2,25,2,2,2,...,1,0,2,5,1,1,2,2,4,0
6,Nissan,2,1,2,1,3,0,27,1,6,...,0,1,0,0,0,1,2,2,2,1
7,Chevrolet,2,0,2,0,2,1,4,16,2,...,1,0,0,0,1,0,1,1,0,2
8,Hyundai,1,1,1,1,1,0,3,0,20,...,0,0,0,2,0,0,1,0,0,2
9,Mazda,0,4,0,0,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
10,Renault,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,1,0,1
11,Lamborghini,0,0,0,0,1,0,0,0,1,...,29,0,0,0,0,1,0,1,0,0
12,Mercedes-Benz,2,1,4,7,4,7,3,2,7,...,5,25,9,5,4,7,9,13,9,5
13,BMW,5,6,3,10,5,6,4,2,7,...,6,13,25,3,8,9,7,12,9,6
14,Ford,16,7,17,10,12,4,6,17,11,...,1,1,3,27,7,2,8,2,6,16
15,Porsche,0,2,2,0,3,2,0,1,2,...,4,2,0,0,27,6,5,6,0,1
16,Audi,3,1,2,2,2,0,2,0,3,...,3,3,3,1,0,24,5,2,3,1
17,Volkswagen,2,9,2,4,3,5,6,2,7,...,0,7,6,7,1,6,17,1,2,2
18,Ferrari,0,0,1,0,3,0,1,1,3,...,17,1,0,1,4,2,1,24,1,2
19,Lexus,0,0,0,0,0,0,0,1,2,...,0,0,0,2,0,0,3,0,25,0
20,Volvo,0,0,0,0,0,0,0,1,0,...,0,0,0,1,1,1,1,0,0,22

In [4]:
df2

,Unnamed: 0,The car brand Jeep is similar to,The car brand Subaru is similar to,The car brand Dodge is similar to,The car brand Tesla is similar to,The car brand Toyota is similar to,The car brand Honda is similar to,The car brand Nissan is similar to,The car brand Chevrolet is similar to,The car brand Hyundai is similar to,...,The car brand Lamborghini is similar to,The car brand Mercedes-Benz is similar to,The car brand BMW is similar to,The car brand Ford is similar to,The car brand Porsche is similar to,The car brand Audi is similar to,The car brand Volkswagen is similar to,The car brand Ferrari is similar to,The car brand Lexus is similar to,The car brand Volvo is similar to
0,Jeep,21,0,2,1,0,1,0,0,1,...,0,0,0,3,0,1,1,3,0,0
1,Subaru,0,24,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,2,0
2,Dodge,0,0,25,0,0,0,0,0,0,...,0,0,0,0,0,2,0,0,1,0
3,Tesla,1,3,0,27,2,1,6,6,1,...,2,5,2,6,4,2,5,2,1,6
4,Toyota,3,7,4,1,24,5,5,6,5,...,0,2,5,5,0,0,3,1,4,1
5,Honda,0,5,0,1,6,25,0,2,1,...,3,0,2,1,0,0,0,2,1,1
6,Nissan,0,2,1,1,4,0,25,1,6,...,1,0,1,1,1,0,0,0,3,1
7,Chevrolet,1,1,1,1,0,2,1,17,2,...,0,0,1,2,0,1,0,0,1,1
8,Hyundai,0,0,1,0,0,1,0,1,23,...,0,2,0,1,0,0,0,0,0,0
9,Mazda,0,1,0,0,1,2,0,0,0,...,1,0,0,1,0,0,0,0,0,0
10,Renault,0,0,0,0,0,1,1,0,0,...,0,0,1,1,0,1,1,1,0,0
11,Lamborghini,0,0,0,0,0,0,0,0,0,...,26,0,0,0,1,1,0,0,0,0
12,Mercedes-Benz,2,4,3,4,3,1,2,4,4,...,4,22,12,0,9,9,4,9,12,3
13,BMW,0,6,8,7,4,4,6,1,3,...,4,5,25,8,6,12,4,9,9,10
14,Ford,20,7,17,8,7,3,6,14,10,...,1,5,6,26,3,3,7,4,6,10
15,Porsche,0,1,2,3,1,1,0,2,2,...,3,1,4,1,25,6,4,7,2,3
16,Audi,0,0,1,0,0,0,1,2,0,...,2,1,2,0,6,28,5,2,3,3
17,Volkswagen,2,3,1,2,4,6,6,3,8,...,1,4,3,3,6,5,17,3,1,3
18,Ferrari,2,1,0,1,1,2,4,0,3,...,15,2,1,0,5,2,2,20,1,0
19,Lexus,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,26,0
20,Volvo,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,1,0,0,1,26

In [5]:
joined = df1+df2+df3+df4+df5+df6+df7+df8+df9+df10
joined

,Unnamed: 0,The car brand Jeep is similar to,The car brand Subaru is similar to,The car brand Dodge is similar to,The car brand Tesla is similar to,The car brand Toyota is similar to,The car brand Honda is similar to,The car brand Nissan is similar to,The car brand Chevrolet is similar to,The car brand Hyundai is similar to,...,The car brand Lamborghini is similar to,The car brand Mercedes-Benz is similar to,The car brand BMW is similar to,The car brand Ford is similar to,The car brand Porsche is similar to,The car brand Audi is similar to,The car brand Volkswagen is similar to,The car brand Ferrari is similar to,The car brand Lexus is similar to,The car brand Volvo is similar to
0,JeepJeepJeepJeepJeepJeepJeepJeepJeepJeep,235,0,21,2,9,8,2,6,5,...,4,5,6,15,2,4,12,21,3,4
1,SubaruSubaruSubaruSubaruSubaruSubaruSubaruSuba...,4,281,2,0,1,3,6,0,2,...,1,3,0,2,1,0,3,0,3,5
2,DodgeDodgeDodgeDodgeDodgeDodgeDodgeDodgeDodgeD...,8,1,233,0,4,1,0,2,0,...,0,1,0,2,0,2,1,1,1,0
3,TeslaTeslaTeslaTeslaTeslaTeslaTeslaTeslaTeslaT...,13,12,7,262,20,8,38,48,24,...,22,44,29,28,24,25,25,12,28,36
4,ToyotaToyotaToyotaToyotaToyotaToyotaToyotaToyo...,52,65,27,20,243,78,66,37,62,...,4,23,25,43,11,16,26,15,65,18
5,HondaHondaHondaHondaHondaHondaHondaHondaHondaH...,12,34,15,10,35,258,22,8,23,...,5,7,9,16,4,6,7,11,28,9
6,NissanNissanNissanNissanNissanNissanNissanNiss...,11,20,16,13,27,20,260,11,29,...,3,10,5,15,5,5,7,7,15,6
7,ChevroletChevroletChevroletChevroletChevroletC...,16,2,24,6,10,7,8,181,7,...,2,4,6,15,4,5,12,5,8,13
8,HyundaiHyundaiHyundaiHyundaiHyundaiHyundaiHyun...,3,9,8,3,7,7,10,3,230,...,0,2,1,10,1,1,7,1,6,7
9,MazdaMazdaMazdaMazdaMazdaMazdaMazdaMazdaMazdaM...,2,9,2,0,5,18,1,4,5,...,1,3,1,7,0,1,2,1,2,0
10,RenaultRenaultRenaultRenaultRenaultRenaultRena...,0,1,0,0,1,5,7,1,4,...,1,2,3,3,1,4,2,6,0,2
11,LamborghiniLamborghiniLamborghiniLamborghiniLa...,1,0,1,2,4,2,1,0,1,...,277,2,2,1,5,6,2,11,1,0
12,Mercedes-BenzMercedes-BenzMercedes-BenzMercede...,17,24,31,50,37,58,46,25,38,...,54,201,111,44,48,98,58,107,80,66
13,BMWBMWBMWBMWBMWBMWBMWBMWBMWBMW,21,69,64,81,51,50,56,15,41,...,25,80,244,71,63,119,57,76,77,72
14,FordFordFordFordFordFordFordFordFordFord,204,68,155,84,94,56,54,174,111,...,19,40,45,264,65,24,68,24,65,108
15,PorschePorschePorschePorschePorschePorschePors...,4,7,14,17,19,8,11,14,11,...,37,23,21,17,264,46,45,42,15,13
16,AudiAudiAudiAudiAudiAudiAudiAudiAudiAudi,10,9,9,11,7,12,12,8,15,...,19,24,22,8,30,245,61,23,32,15
17,VolkswagenVolkswagenVolkswagenVolkswagenVolksw...,15,64,21,30,44,47,55,28,70,...,9,41,34,52,37,49,179,29,23,22
18,FerrariFerrariFerrariFerrariFerrariFerrariFerr...,8,9,6,6,8,10,16,3,21,...,179,27,12,8,51,22,16,227,16,6
19,LexusLexusLexusLexusLexusLexusLexusLexusLexusL...,2,2,2,1,9,6,2,4,4,...,3,1,1,3,0,2,3,1,263,0
20,VolvoVolvoVolvoVolvoVolvoVolvoVolvoVolvoVolvoV...,2,1,2,1,0,0,4,2,3,...,1,2,1,9,3,7,2,0,3,220

In [6]:
joined['Unnamed: 0'] = df1['Unnamed: 0']

In [7]:
joined

,Unnamed: 0,The car brand Jeep is similar to,The car brand Subaru is similar to,The car brand Dodge is similar to,The car brand Tesla is similar to,The car brand Toyota is similar to,The car brand Honda is similar to,The car brand Nissan is similar to,The car brand Chevrolet is similar to,The car brand Hyundai is similar to,...,The car brand Lamborghini is similar to,The car brand Mercedes-Benz is similar to,The car brand BMW is similar to,The car brand Ford is similar to,The car brand Porsche is similar to,The car brand Audi is similar to,The car brand Volkswagen is similar to,The car brand Ferrari is similar to,The car brand Lexus is similar to,The car brand Volvo is similar to
0,Jeep,235,0,21,2,9,8,2,6,5,...,4,5,6,15,2,4,12,21,3,4
1,Subaru,4,281,2,0,1,3,6,0,2,...,1,3,0,2,1,0,3,0,3,5
2,Dodge,8,1,233,0,4,1,0,2,0,...,0,1,0,2,0,2,1,1,1,0
3,Tesla,13,12,7,262,20,8,38,48,24,...,22,44,29,28,24,25,25,12,28,36
4,Toyota,52,65,27,20,243,78,66,37,62,...,4,23,25,43,11,16,26,15,65,18
5,Honda,12,34,15,10,35,258,22,8,23,...,5,7,9,16,4,6,7,11,28,9
6,Nissan,11,20,16,13,27,20,260,11,29,...,3,10,5,15,5,5,7,7,15,6
7,Chevrolet,16,2,24,6,10,7,8,181,7,...,2,4,6,15,4,5,12,5,8,13
8,Hyundai,3,9,8,3,7,7,10,3,230,...,0,2,1,10,1,1,7,1,6,7
9,Mazda,2,9,2,0,5,18,1,4,5,...,1,3,1,7,0,1,2,1,2,0
10,Renault,0,1,0,0,1,5,7,1,4,...,1,2,3,3,1,4,2,6,0,2
11,Lamborghini,1,0,1,2,4,2,1,0,1,...,277,2,2,1,5,6,2,11,1,0
12,Mercedes-Benz,17,24,31,50,37,58,46,25,38,...,54,201,111,44,48,98,58,107,80,66
13,BMW,21,69,64,81,51,50,56,15,41,...,25,80,244,71,63,119,57,76,77,72
14,Ford,204,68,155,84,94,56,54,174,111,...,19,40,45,264,65,24,68,24,65,108
15,Porsche,4,7,14,17,19,8,11,14,11,...,37,23,21,17,264,46,45,42,15,13
16,Audi,10,9,9,11,7,12,12,8,15,...,19,24,22,8,30,245,61,23,32,15
17,Volkswagen,15,64,21,30,44,47,55,28,70,...,9,41,34,52,37,49,179,29,23,22
18,Ferrari,8,9,6,6,8,10,16,3,21,...,179,27,12,8,51,22,16,227,16,6
19,Lexus,2,2,2,1,9,6,2,4,4,...,3,1,1,3,0,2,3,1,263,0
20,Volvo,2,1,2,1,0,0,4,2,3,...,1,2,1,9,3,7,2,0,3,220

In [8]:
joined.to_csv("freqs/j Nov 30 420.csv")